CREATE (:Event {name: 'earthquake', description: '...'});
CREATE (:Event {name: 'terrorist attack', description: '...'});
CREATE (:Event {name: 'industrial accident', description: '...'});
CREATE (:Event {name: 'flood', description: '...'});
CREATE (:Event {name: 'fire', description: '...'});

CREATE (:CascadingWNEvent {name:'pipe break', description: '...'});
CREATE (:CascadingWNEvent {name:'source contamination', description: '...'});

CREATE (:ProducedEvent {name:'sewage infiltration', description: '...'});
CREATE (:ProducedEvent {name:'water loss', description: '...'});
CREATE (:ProducedEvent {name:'sewage pathogens', description: '...'});
CREATE (:ProducedEvent {name:'industrial chemicals', description: '...'});
CREATE (:ProducedEvent {name:'soil pathogens', description: '...'});

CREATE (:EffectWaterTaste {name:'metallic-bitter'});
CREATE (:EffectWaterTaste {name:'earthy-musty'});
CREATE (:EffectWaterTaste {name:'petrol-diesel'});
CREATE (:EffectWaterTaste {name:'sewage-taste'});
CREATE (:EffectWaterTaste {name:'sweet'});
CREATE (:EffectWaterTaste {name:'chemical'});
CREATE (:EffectWaterTaste {name:'chlorine-bleach'});

CREATE (:EffectWaterOdor {name:'sewage smell'});
CREATE (:EffectWaterOdor {name:'roten eggs'});
CREATE (:EffectWaterOdor {name:'sulfur'});
CREATE (:EffectWaterOdor {name:'metal'});

CREATE (:EffectWater {name:'brown'});
CREATE (:EffectWater {name:'yellow'});
CREATE (:EffectWater {name:'blue'});
CREATE (:EffectWater {name:'rasty'});

CREATE (:EffectHealth {name:'gastroenteritis'});
CREATE (:EffectHealth {name:'salmonellosis'});
CREATE (:EffectHealth {name:'typhoid'});
CREATE (:EffectHealth {name:'cholera'});
CREATE (:EffectHealth {name:'respiratory'});
CREATE (:EffectHealth {name:'cryptosporidiosis'});

CREATE (:Contaminant {name:'ecoli'});
CREATE (:Contaminant {name:'salmonella'});
CREATE (:Contaminant {name:'campylobacter'});
CREATE (:Contaminant {name:'enterovirus'});
CREATE (:Contaminant {name:'norovirus'});
CREATE (:Contaminant {name:'rotavirus'});
CREATE (:Contaminant {name:'astrovirus'});
CREATE (:Contaminant {name:'cholerae'});
CREATE (:Contaminant {name:'cryptosporidium'});
CREATE (:Contaminant {name:'giardia'});
CREATE (:Contaminant {name:'bacillus'});
CREATE (:Contaminant {name:'brucella'});
CREATE (:Contaminant {name:'toxoplasma'});
CREATE (:Contaminant {name:'botulinum'});
CREATE (:Contaminant {name:'microcystins'});
CREATE (:Contaminant {name:'saxitoxin'});
CREATE (:Contaminant {name:'ricin'});
CREATE (:Contaminant {name:'arsenic'});
CREATE (:Contaminant {name:'diesel'});
CREATE (:Contaminant {name:'oil'});
CREATE (:Contaminant {name:'aldicarb'});
CREATE (:Contaminant {name:'legionella'});

CREATE (:Symptom {name:'diarrhea'});
CREATE (:Symptom {name:'vomit'});
CREATE (:Symptom {name:'anemia'});
CREATE (:Symptom {name:'weight loss'});
CREATE (:Symptom {name:'fever'});
CREATE (:Symptom {name:'abdomnal pain'});
CREATE (:Symptom {name:'muscle ache'});
CREATE (:Symptom {name:'insomia'});
CREATE (:Symptom {name:'anorexia'});
CREATE (:Symptom {name:'coughing'});
CREATE (:Symptom {name:'chestpain'});
CREATE (:Symptom {name:'respiratory infection'});
CREATE (:Symptom {name:'death'});
CREATE (:Symptom {name:'miscarrage'});
CREATE (:Symptom {name:'paralysis'});

CREATE (:ContaminantFamily {name:'bacteria'});
CREATE (:ContaminantFamily {name:'virus'});
CREATE (:ContaminantFamily {name:'protozoa'});
CREATE (:ContaminantFamily {name:'bacterial toxin'});
CREATE (:ContaminantFamily {name:'algal'});
CREATE (:ContaminantFamily {name:'plant'});
CREATE (:ContaminantFamily {name:'metals'});
CREATE (:ContaminantFamily {name:'hydrophobic'});
CREATE (:ContaminantFamily {name:'presticides'});

CREATE (:ContaminantType {name:'biohazards'});
CREATE (:ContaminantType {name:'toxin'});
CREATE (:ContaminantType {name:'chemical'});
CREATE (:ContaminantFamily {name:'copper'});
CREATE (:ContaminantFamily {name: 'petrol'});

CREATE (:ContaminantTreatment {name:'activated-alumina'});
CREATE (:ContaminantTreatment {name:'coagulants'});
CREATE (:ContaminantTreatment {name:'lime-softening'});
CREATE (:ContaminantTreatment {name:'chlorination'});
CREATE (:ContaminantTreatment {name:'chlorine-dioxide'});
CREATE (:ContaminantTreatment {name:'ozone'});
CREATE (:ContaminantTreatment {name:'uv'});
CREATE (:ContaminantTreatment {name:'thermal inactivation'});
CREATE (:ContaminantTreatment {name:'metal ionization'});

MATCH (e:Event) WITH e MATCH (ce:CascadingWNEvent) WHERE e.name='earthquake' and ce.name='pipe break' CREATE (e)-[cp:CAN_PRODUCE]->(ce);
MATCH (e:Event) WITH e MATCH (ce:CascadingWNEvent) WHERE e.name='earthquake' and ce.name='source contamination' CREATE (e)-[cp:CAN_PRODUCE]->(ce);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='pipe break' and pe.name='sewage infiltration' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='pipe break' and pe.name='water loss' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='pipe break' and pe.name='sewage pathogens' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='pipe break' and pe.name='industrial chemicals' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='source contamination' and pe.name='soil pathogens' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (ce:CascadingWNEvent) WITH ce MATCH (pe:ProducedEvent) WHERE ce.name='source contamination' and pe.name='industrial chemicals' CREATE (ce)-[cc:CAN_CAUSE]->(pe);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='ecoli' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='campylobacter' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='salmonella' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='cholerae' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='astrovirus' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (pe:ProducedEvent) WITH pe MATCH (co:Contaminant) WHERE co.name='rotavirus' and pe.name='sewage pathogens' CREATE (pe)-[:CAN_PRODUCE]->(co);
MATCH (co:Contaminant) WITH co MATCH (cf:ContaminantFamily) WHERE co.name='ecoli' and cf.name='bacteria' CREATE (co)-[fam:FAMILY]->(cf);
MATCH (co:Contaminant) WITH co MATCH (cf:ContaminantFamily) WHERE co.name='rotavirus' and cf.name='virus' CREATE (co)-[fam:FAMILY]->(cf);
MATCH (co:Contaminant) WITH co MATCH (cf:ContaminantFamily) WHERE co.name='giardia' and cf.name='protozoa' CREATE (co)-[fam:FAMILY]->(cf);
MATCH (cf:ContaminantFamily) WITH cf MATCH (ct:ContaminantType) WHERE cf.name='bacteria' and ct.name='biohazards' CREATE (cf)-[t:TYPE]->(ct);
MATCH (cf:ContaminantFamily) WITH cf MATCH (ct:ContaminantType) WHERE cf.name='virus' and ct.name='biohazards' CREATE (cf)-[t:TYPE]->(ct);
MATCH (c:Contaminant) WITH c MATCH (eh:EffectHealth) WHERE c.name='ecoli' and eh.name='gastroenteritis' CREATE (c)-[cc:CAN_CAUSE]->(eh);
MATCH (eh:EffectHealth) WITH eh MATCH (s:Symptom) WHERE eh.name='gastroenteritis' and s.name='diarrhea' CREATE (eh)-[cc:HAS_SYMPTOMS]->(s);
MATCH (eh:EffectHealth) WITH eh MATCH (s:Symptom) WHERE eh.name='gastroenteritis' and s.name='vomit' CREATE (eh)-[cc:HAS_SYMPTOMS]->(s);
MATCH (cf:ContaminantFamily) WITH cf MATCH (ewt:EffectWaterTaste) WHERE cf.name='bacteria' and ewt.name='earthy-musty' CREATE (cf)-[ct:CAN_TASTE]->(ewt);
MATCH (cf:ContaminantFamily) WITH cf MATCH (ewt:EffectWaterTaste) WHERE cf.name='copper' and ewt.name='metallic-bitter' CREATE (cf)-[ct:CAN_TASTE]->(ewt);
MATCH (cf:ContaminantFamily) WITH cf MATCH (ewt:EffectWaterTaste) WHERE cf.name='petrol' and ewt.name='petrol-diesel' CREATE (cf)-[ct:CAN_TASTE]->(ewt);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='ecoli' and ct.name='chlorination' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='ecoli' and ct.name='chlorine-dioxide' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='ecoli' and ct.name='ozone' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='ecoli' and ct.name='uv' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='bacillus' and ct.name='chlorination' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='arsenic' and ct.name='activated-alumina' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='arsenic' and ct.name='coagulants' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='arsenic' and ct.name='lime-softening' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='toxoplasma' and ct.name='chlorination' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='toxoplasma' and ct.name='uv' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='cryptosporidium' and ct.name='thermal inactivation' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='legionella' and ct.name='thermal inactivation' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='legionella' and ct.name='uv' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='legionella' and ct.name='chlorination' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='legionella' and ct.name='chlorine-dioxide' CREATE (c)-[it:IS_TREATED]->(ct);
MATCH (c:Contaminant) WITH c MATCH (ct:ContaminantTreatment) WHERE c.name='legionella' and ct.name='metal ionization' CREATE (c)-[it:IS_TREATED]->(ct);