# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EmergencyMultiselectOptionsSymptoms(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None):  # noqa: E501
        """EmergencyMultiselectOptionsSymptoms - a model defined in Swagger

        :param key: The key of this EmergencyMultiselectOptionsSymptoms.  # noqa: E501
        :type key: str
        """
        self.swagger_types = {
            'key': str
        }

        self.attribute_map = {
            'key': 'key'
        }
        self._key = key

    @classmethod
    def from_dict(cls, dikt) -> 'EmergencyMultiselectOptionsSymptoms':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmergencyMultiselectOptions_symptoms of this EmergencyMultiselectOptionsSymptoms.  # noqa: E501
        :rtype: EmergencyMultiselectOptionsSymptoms
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this EmergencyMultiselectOptionsSymptoms.


        :return: The key of this EmergencyMultiselectOptionsSymptoms.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this EmergencyMultiselectOptionsSymptoms.


        :param key: The key of this EmergencyMultiselectOptionsSymptoms.
        :type key: str
        """

        self._key = key
