# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.emergency_multiselect_options_symptoms import EmergencyMultiselectOptionsSymptoms  # noqa: F401,E501
from swagger_server import util


class EmergencyMultiselectOptions(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, symptoms: EmergencyMultiselectOptionsSymptoms=None, detections: EmergencyMultiselectOptionsSymptoms=None, contaminants: EmergencyMultiselectOptionsSymptoms=None):  # noqa: E501
        """EmergencyMultiselectOptions - a model defined in Swagger

        :param symptoms: The symptoms of this EmergencyMultiselectOptions.  # noqa: E501
        :type symptoms: EmergencyMultiselectOptionsSymptoms
        :param detections: The detections of this EmergencyMultiselectOptions.  # noqa: E501
        :type detections: EmergencyMultiselectOptionsSymptoms
        :param contaminants: The contaminants of this EmergencyMultiselectOptions.  # noqa: E501
        :type contaminants: EmergencyMultiselectOptionsSymptoms
        """
        self.swagger_types = {
            'symptoms': EmergencyMultiselectOptionsSymptoms,
            'detections': EmergencyMultiselectOptionsSymptoms,
            'contaminants': EmergencyMultiselectOptionsSymptoms
        }

        self.attribute_map = {
            'symptoms': 'symptoms',
            'detections': 'detections',
            'contaminants': 'contaminants'
        }
        self._symptoms = symptoms
        self._detections = detections
        self._contaminants = contaminants

    @classmethod
    def from_dict(cls, dikt) -> 'EmergencyMultiselectOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmergencyMultiselectOptions of this EmergencyMultiselectOptions.  # noqa: E501
        :rtype: EmergencyMultiselectOptions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def symptoms(self) -> EmergencyMultiselectOptionsSymptoms:
        """Gets the symptoms of this EmergencyMultiselectOptions.


        :return: The symptoms of this EmergencyMultiselectOptions.
        :rtype: EmergencyMultiselectOptionsSymptoms
        """
        return self._symptoms

    @symptoms.setter
    def symptoms(self, symptoms: EmergencyMultiselectOptionsSymptoms):
        """Sets the symptoms of this EmergencyMultiselectOptions.


        :param symptoms: The symptoms of this EmergencyMultiselectOptions.
        :type symptoms: EmergencyMultiselectOptionsSymptoms
        """

        self._symptoms = symptoms

    @property
    def detections(self) -> EmergencyMultiselectOptionsSymptoms:
        """Gets the detections of this EmergencyMultiselectOptions.


        :return: The detections of this EmergencyMultiselectOptions.
        :rtype: EmergencyMultiselectOptionsSymptoms
        """
        return self._detections

    @detections.setter
    def detections(self, detections: EmergencyMultiselectOptionsSymptoms):
        """Sets the detections of this EmergencyMultiselectOptions.


        :param detections: The detections of this EmergencyMultiselectOptions.
        :type detections: EmergencyMultiselectOptionsSymptoms
        """

        self._detections = detections

    @property
    def contaminants(self) -> EmergencyMultiselectOptionsSymptoms:
        """Gets the contaminants of this EmergencyMultiselectOptions.


        :return: The contaminants of this EmergencyMultiselectOptions.
        :rtype: EmergencyMultiselectOptionsSymptoms
        """
        return self._contaminants

    @contaminants.setter
    def contaminants(self, contaminants: EmergencyMultiselectOptionsSymptoms):
        """Sets the contaminants of this EmergencyMultiselectOptions.


        :param contaminants: The contaminants of this EmergencyMultiselectOptions.
        :type contaminants: EmergencyMultiselectOptionsSymptoms
        """

        self._contaminants = contaminants
