# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.emergency_links_orgarchived import EmergencyLinksOrgarchived  # noqa: F401,E501
from swagger_server.models.emergency_links_self import EmergencyLinksSelf  # noqa: F401,E501
from swagger_server import util


class EmergencyLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_archived: EmergencyLinksOrgarchived=None, _self: EmergencyLinksSelf=None):  # noqa: E501
        """EmergencyLinks - a model defined in Swagger

        :param org_archived: The org_archived of this EmergencyLinks.  # noqa: E501
        :type org_archived: EmergencyLinksOrgarchived
        :param _self: The _self of this EmergencyLinks.  # noqa: E501
        :type _self: EmergencyLinksSelf
        """
        self.swagger_types = {
            'org_archived': EmergencyLinksOrgarchived,
            '_self': EmergencyLinksSelf
        }

        self.attribute_map = {
            'org_archived': 'org-archived',
            '_self': 'self'
        }
        self._org_archived = org_archived
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'EmergencyLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Emergency__links of this EmergencyLinks.  # noqa: E501
        :rtype: EmergencyLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_archived(self) -> EmergencyLinksOrgarchived:
        """Gets the org_archived of this EmergencyLinks.


        :return: The org_archived of this EmergencyLinks.
        :rtype: EmergencyLinksOrgarchived
        """
        return self._org_archived

    @org_archived.setter
    def org_archived(self, org_archived: EmergencyLinksOrgarchived):
        """Sets the org_archived of this EmergencyLinks.


        :param org_archived: The org_archived of this EmergencyLinks.
        :type org_archived: EmergencyLinksOrgarchived
        """

        self._org_archived = org_archived

    @property
    def _self(self) -> EmergencyLinksSelf:
        """Gets the _self of this EmergencyLinks.


        :return: The _self of this EmergencyLinks.
        :rtype: EmergencyLinksSelf
        """
        return self.__self

    @_self.setter
    def _self(self, _self: EmergencyLinksSelf):
        """Sets the _self of this EmergencyLinks.


        :param _self: The _self of this EmergencyLinks.
        :type _self: EmergencyLinksSelf
        """

        self.__self = _self
