# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200LinksMyuser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, href: str=None):  # noqa: E501
        """InlineResponse200LinksMyuser - a model defined in Swagger

        :param href: The href of this InlineResponse200LinksMyuser.  # noqa: E501
        :type href: str
        """
        self.swagger_types = {
            'href': str
        }

        self.attribute_map = {
            'href': 'href'
        }
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200LinksMyuser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200__links_myuser of this InlineResponse200LinksMyuser.  # noqa: E501
        :rtype: InlineResponse200LinksMyuser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """Gets the href of this InlineResponse200LinksMyuser.


        :return: The href of this InlineResponse200LinksMyuser.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this InlineResponse200LinksMyuser.


        :param href: The href of this InlineResponse200LinksMyuser.
        :type href: str
        """

        self._href = href
