# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_links import InlineResponse200Links  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, links: InlineResponse200Links=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param token: The token of this InlineResponse200.  # noqa: E501
        :type token: str
        :param links: The links of this InlineResponse200.  # noqa: E501
        :type links: InlineResponse200Links
        """
        self.swagger_types = {
            'token': str,
            'links': InlineResponse200Links
        }

        self.attribute_map = {
            'token': 'token',
            'links': '_links'
        }
        self._token = token
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this InlineResponse200.


        :return: The token of this InlineResponse200.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this InlineResponse200.


        :param token: The token of this InlineResponse200.
        :type token: str
        """

        self._token = token

    @property
    def links(self) -> InlineResponse200Links:
        """Gets the links of this InlineResponse200.


        :return: The links of this InlineResponse200.
        :rtype: InlineResponse200Links
        """
        return self._links

    @links.setter
    def links(self, links: InlineResponse200Links):
        """Sets the links of this InlineResponse200.


        :param links: The links of this InlineResponse200.
        :type links: InlineResponse200Links
        """

        self._links = links
