# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.emergency_links_orgarchived import EmergencyLinksOrgarchived  # noqa: F401,E501
from swagger_server.models.inline_response200_links_myorg import InlineResponse200LinksMyorg  # noqa: F401,E501
from swagger_server.models.inline_response200_links_myuser import InlineResponse200LinksMyuser  # noqa: F401,E501
from swagger_server import util


class InlineResponse200Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_archived: EmergencyLinksOrgarchived=None, my_user: InlineResponse200LinksMyuser=None, my_org: InlineResponse200LinksMyorg=None):  # noqa: E501
        """InlineResponse200Links - a model defined in Swagger

        :param org_archived: The org_archived of this InlineResponse200Links.  # noqa: E501
        :type org_archived: EmergencyLinksOrgarchived
        :param my_user: The my_user of this InlineResponse200Links.  # noqa: E501
        :type my_user: InlineResponse200LinksMyuser
        :param my_org: The my_org of this InlineResponse200Links.  # noqa: E501
        :type my_org: InlineResponse200LinksMyorg
        """
        self.swagger_types = {
            'org_archived': EmergencyLinksOrgarchived,
            'my_user': InlineResponse200LinksMyuser,
            'my_org': InlineResponse200LinksMyorg
        }

        self.attribute_map = {
            'org_archived': 'org-archived',
            'my_user': 'my-user',
            'my_org': 'my-org'
        }
        self._org_archived = org_archived
        self._my_user = my_user
        self._my_org = my_org

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200__links of this InlineResponse200Links.  # noqa: E501
        :rtype: InlineResponse200Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_archived(self) -> EmergencyLinksOrgarchived:
        """Gets the org_archived of this InlineResponse200Links.


        :return: The org_archived of this InlineResponse200Links.
        :rtype: EmergencyLinksOrgarchived
        """
        return self._org_archived

    @org_archived.setter
    def org_archived(self, org_archived: EmergencyLinksOrgarchived):
        """Sets the org_archived of this InlineResponse200Links.


        :param org_archived: The org_archived of this InlineResponse200Links.
        :type org_archived: EmergencyLinksOrgarchived
        """

        self._org_archived = org_archived

    @property
    def my_user(self) -> InlineResponse200LinksMyuser:
        """Gets the my_user of this InlineResponse200Links.


        :return: The my_user of this InlineResponse200Links.
        :rtype: InlineResponse200LinksMyuser
        """
        return self._my_user

    @my_user.setter
    def my_user(self, my_user: InlineResponse200LinksMyuser):
        """Sets the my_user of this InlineResponse200Links.


        :param my_user: The my_user of this InlineResponse200Links.
        :type my_user: InlineResponse200LinksMyuser
        """

        self._my_user = my_user

    @property
    def my_org(self) -> InlineResponse200LinksMyorg:
        """Gets the my_org of this InlineResponse200Links.


        :return: The my_org of this InlineResponse200Links.
        :rtype: InlineResponse200LinksMyorg
        """
        return self._my_org

    @my_org.setter
    def my_org(self, my_org: InlineResponse200LinksMyorg):
        """Sets the my_org of this InlineResponse200Links.


        :param my_org: The my_org of this InlineResponse200Links.
        :type my_org: InlineResponse200LinksMyorg
        """

        self._my_org = my_org
